### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by shadoxxhd** [hellrage/NC-Reactor-Planner#11]
Using the last non-overhaul version, when starting the program I get a 'has stopped working' dialog.
In gdb I got the following error:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at NC_Reactor_Planner.Configuration.Save(FileInfo file)
   at NC_Reactor_Planner.Program.PreStartUp()
   at NC_Reactor_Planner.Program.Main(String[] args)
gdb: unknown target exception 0xe0434352 at 0x7793c5af
```

**Comment by shadoxxhd** [comment]
I actually have the same issue with the newest overhaul release (2.0.18).

**Comment by hellrage** [comment]
Hmm, is this for a clean launch? I.E. no dlls \ configs next to the exe.

**Comment by shadoxxhd** [comment]
It was not. When placing it in a new directory, it works just fine.

**Comment by shadoxxhd** [comment]
There was another version of your json library in the directory, which apparently confused the reactor planner.

**Comment by hellrage** [comment]
Good to know!
