### ISSUE TITLE
Import Button Inactive

### ISSUE THREAD

**Issue by WugWugg** [hellrage/NC-Reactor-Planner#12]
I've tried to work with this application on versions 2.0.24 and 2.0.22, but they both will not let me import a custom .cfg file as the button appears inactive. The "apply", "load", and "save" buttons all are active and work.

**Comment by hellrage** [comment]
2.x are overhaul versions (NC doesn't have these mechanics implemented yet so there is nothing to import), for the current release of NC you need 1.x "Latest release" tagged version (1.2.21 iirc)
