### ISSUE TITLE
[Feature Request] Write reactor stats to saved jsons

### ISSUE THREAD

**Issue by tomdodd4598** [hellrage/NC-Reactor-Planner#21]
As well as writing all of the information required for the planner to read the design and load it into the planner, would it be possible to write the reactor's stats too, for data processing programs and such? I'm not sure the info on the individual clusters is necessary, but the overall reactor info could be very useful :)

**Comment by hellrage** [comment]
Reactor stats are now written to savefile jsons as of 107390c75fcca2cc20a0395b0af631ded0356e1d
Thanks for posting the issue!
