### ISSUE TITLE
[Reminder] Present and future heat sink changes

### ISSUE THREAD

**Issue by tomdodd4598** [hellrage/NC-Reactor-Planner#23]
Just leaving this here so that the reactor planner and NC end up in sync :P

There are currently three changes in NC that are not in the latest planner (2.0.33) by default:
**Slime:** 1 reflector + exactly 1 water  -->  **exactly 1 water + 2 lead**
**Lithium:** exactly 2 lead + casing  -->  **2 axial lead + casing**
**Liquid nitrogen:** 1 copper + 2 lead  -->  **2 copper + 1 purpur**

There will also be more tweaks in the future to account for some sinks being rarely used in the designs so far posted to the Discord server :)

**Comment by hellrage** [comment]
Hello! Thanks for posting the reminder! The mentioned changes have been implemented in 107390c75fcca2cc20a0395b0af631ded0356e1d
