### ISSUE TITLE
Custom active cooling value not taken into account

### ISSUE THREAD

**Issue by Eusebius** [hellrage/NC-Reactor-Planner#30]
[v1.2.23, pre-overhaul] When this value is changed in the config, it doesn't impact the tooltips in the block palette, or the stats of the reactor. Setting _passive_ cooling values seems to work as intended.

**Comment by hellrage** [comment]
Hello, I can't reproduce the issue in my instance, can you describe your exact steps? Are you using the config UI or editing the .json ?

**Comment by Eusebius** [comment]
Apparently it was a mistake on my side, sorry, I got confused with active cooling max rate.
