### ISSUE TITLE
[Suggestion] Text import/export for JSON

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [hellrage/NC-Reactor-Planner#31]
Add an option to import or export to a string of text, rather than only to a file

This would allow for quick copy-paste between the planner and my reactor generator

**Comment by hellrage** [comment]
Pre-overhaul added in 55fb4bd5541d65f25c8e15ba765a4c672fdc9367

**Comment by hellrage** [comment]
Overhaul added in 3b179537829328067e74f0e3aae73c0b09d9095c
