### ISSUE TITLE
BG String does not include active coolers

### ISSUE THREAD

**Issue by mkaito** [hellrage/NC-Reactor-Planner#44]
Version 1.2.25

When exporting active coolers to BG string, they should be converted to "Active Fluid Cooler" blocks.

See reactor design and BG string below.

Reactor save
https://files.mkaito.net/2dd37af68023946e76ff6635439cf0a924f2d59c.json

BG export
https://files.mkaito.net/701fb190ffcc02953c78c41c5f4c6d7c925801dd.json

**Comment by hellrage** [comment]
Hello!
BG didn't support tile entities when I implemented the export, AFAIK it still doesn't. It's intended that active coolers aren't placed, as I can't include the required tile entities in the export.

**Comment by mkaito** [comment]
I didn't know they were considered tile entities. BG does indeed not support them. Not much you can do about that then. 

Thanks for the fast response!
