### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by mystery-z** [hellrage/NC-Reactor-Planner#49]
Tried the Linux install instructions just converted everything to Mac (eg, apt-get to brew). 
Didn't work and ended up throwing some errors: see [here](https://hastebin.com/apokuzihoj.apache)
Any suggestions / fixes / plans for MacOS support?

**Comment by hellrage** [comment]
Hello! The log shows that you're trying to run Thiz's planner (the one linked in my readme as the successor). You should try asking in the respective repo: https://github.com/ThizThizzyDizzy/nc-reactor-generator
