### ISSUE TITLE
Linux compatible version?

### ISSUE THREAD

**Issue by ShneekeyTheLost** [hellrage/NC-Reactor-Planner#5]
I would really appreciate either having a linux distro version or at least having a MAKE file in the tarball so I can compile myself in MONO. Or at least be able to be ran with WINE. Currently cannot be run through WINE with a bunch of stuff like this:

0026:err:hid:PNP_AddDevice Cannot parse Report Descriptor
0026:err:plugplay:handle_bus_relations AddDevice failed for driver L"WineHID"
then ending with

Unhandled Exception:
System.BadImageFormatException: Could not resolve field token 0x040000da, due to: Could not load type of field 'NC_Reactor_Planner.Reactor:interiorDims' (5) due to: Could not load file or assembly 'PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. assembly:Z:\home\shneekey\Desktop\NC.Reactor.Planner.2.0.10.exe type:Reactor member:(null)

**Comment by brisingraerowing** [comment]
This uses WPF, which isn’t supported by Mono. I’m not sure if it would work on WINE with the .NET framework installed, but it might.

**Comment by hellrage** [comment]
I tried setting up a Mono environment and compiling there but i just can't figure it out, sorry. I did look into how to make the planner available for linux\mac but it's out of my league apparently. So unless i get someone experienced to help or figure it out myself later on, we're out of luck here.
There's a web app in (slow) development here: https://github.com/animusfracto/NC-reactor-app
I'll reopen this or something when there are any developments. Sorry :c

**Comment by Sorixelle** [comment]
I was able to get this to run under WINE 4.21 staging with the following steps:
1. Create a new 32-bit wineprefix
2. Use Winetricks to install `dotnet45`
3. Use winecfg to set the Windows version to Windows 10

**Comment by hellrage** [comment]
Reopening so it's visible in the issues. I'll ask someone in discord to try it out, thanks for letting me know!

**Comment by hellrage** [comment]
Thanks to the above PR we now have linux-compatibility! See instructions in the readme. Starting with 1.2.23 and 2.0.31 the planner should run on linux with the same executable.
