### ISSUE TITLE
Impossible to use

### ISSUE THREAD

**Issue by twothe** [hellrage/NC-Reactor-Planner#9]
When trying to use the latest version to simulate a reactor all I ever get this thing to do is to tell me "No cluster!"

There is no documentation, there is no hint, there is no way to figure out how to use this tool at all, and the tutorial video is heavily outdated.

**Comment by hellrage** [comment]
You downloaded the pre-release overhaul version, it simulates the upcoming changes for the mod that aren't implemented by tom yet. I forgot to put my introduction link in the description, sorry about that, fixed now.
For the current mod versions you need the latest release, 1.2.19
Join Nuclearcraft's discord if you have any questions! https://discord.gg/hdMVZz
